theme: jekyll-theme-caymen
title: Omega Bois
description: Welcome to Omega 101. Here you will find all the information you could ever want about the residents of Omega 101. Viewer discretion is advised 

